language: elixir

matrix:
  include:
    - otp_release: 17.5
      elixir: 1.0.5
    - otp_release: 17.5
      elixir: 1.1.1
    - otp_release: 18.3
      elixir: 1.1.1
    - otp_release: 18.3
      elixir: 1.2.6
    - otp_release: 18.3
      elixir: 1.3.2
    - otp_release: 19.1
      elixir: 1.3.2
    - otp_release: 19.2
      elixir: 1.4.0
    - otp_release: 19.2
      elixir: 1.4.1
    - otp_release: 20.0
      elixir: 1.4.5
    - otp_release: 20.0
      elixir: 1.5.0
    - otp_release: 20.1
      elixir: 1.5.3
    - otp_release: 20.1
      elixir: 1.6.0

sudo: false

script: mix test --trace
